import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface WITItem {
  employeeName: string;
  tin: string;
  isResident: boolean;
  grossWages: number;
  taxWithheld: number;
}

interface WITFormData {
  organizationName: string;
  organizationTIN: string;
  period: string;
  filingDeadline: string;
  items: WITItem[];
  totalWages: number;
  totalTax: number;
}

export function generateWITForm(data: WITFormData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('REPUBLIKA DEMOKRATIKA DE TIMOR-LESTE', pageWidth / 2, 15, { align: 'center' });
  doc.text('MINISTERIO DAS FINANCAS', pageWidth / 2, 20, { align: 'center' });
  doc.text('DIRECCAO NACIONAL DE RECEITAS DOMESTICAS', pageWidth / 2, 25, { align: 'center' });

  // Form Title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('MONTHLY WITHHOLDING INCOME TAX (WIT) RETURN', pageWidth / 2, 35, { align: 'center' });
  doc.text('DECLARACAO MENSAL DE IMPOSTO RETIDO NA FONTE', pageWidth / 2, 42, { align: 'center' });

  // Form Border
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.rect(10, 50, pageWidth - 20, 35);

  // Organization Details
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Employer/Payer Name:', 15, 58);
  doc.setFont('helvetica', 'bold');
  doc.text(data.organizationName, 60, 58);

  doc.setFont('helvetica', 'normal');
  doc.text('TIN:', 15, 65);
  doc.setFont('helvetica', 'bold');
  doc.text(data.organizationTIN || 'N/A', 60, 65);

  doc.setFont('helvetica', 'normal');
  doc.text('Tax Period:', 15, 72);
  doc.setFont('helvetica', 'bold');
  doc.text(data.period, 60, 72);

  doc.setFont('helvetica', 'normal');
  doc.text('Filing Deadline:', 120, 65);
  doc.setFont('helvetica', 'bold');
  doc.text(format(new Date(data.filingDeadline), 'MMMM d, yyyy'), 155, 65);

  // Employee Details Table
  autoTable(doc, {
    startY: 90,
    head: [['No.', 'Employee Name', 'TIN', 'Resident', 'Gross Wages (USD)', 'Tax Withheld (USD)']],
    body: data.items.map((item, index) => [
      index + 1,
      item.employeeName,
      item.tin || '-',
      item.isResident ? 'Yes' : 'No',
      `$${item.grossWages.toFixed(2)}`,
      `$${item.taxWithheld.toFixed(2)}`,
    ]),
    theme: 'grid',
    headStyles: {
      fillColor: [60, 60, 60],
      textColor: 255,
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 9,
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      1: { cellWidth: 50 },
      2: { cellWidth: 30 },
      3: { halign: 'center', cellWidth: 20 },
      4: { halign: 'right', cellWidth: 35 },
      5: { halign: 'right', cellWidth: 35 },
    },
    margin: { left: 10, right: 10 },
  });

  // Summary Section
  const finalY = (doc as any).lastAutoTable.finalY + 10;

  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.rect(pageWidth - 100, finalY, 90, 30);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('SUMMARY', pageWidth - 95, finalY + 8);

  doc.setFont('helvetica', 'normal');
  doc.text('Total Gross Wages:', pageWidth - 95, finalY + 16);
  doc.setFont('helvetica', 'bold');
  doc.text(`$${data.totalWages.toFixed(2)}`, pageWidth - 20, finalY + 16, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.text('Total Tax Withheld:', pageWidth - 95, finalY + 24);
  doc.setFont('helvetica', 'bold');
  doc.text(`$${data.totalTax.toFixed(2)}`, pageWidth - 20, finalY + 24, { align: 'right' });

  // Declaration Section
  const declY = finalY + 45;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('I declare that the information provided above is true and correct to the best of my knowledge.', 10, declY);
  doc.text('Eu declaro que as informacoes fornecidas acima sao verdadeiras e corretas.', 10, declY + 5);

  // Signature Lines
  const sigY = declY + 25;
  doc.line(10, sigY, 80, sigY);
  doc.text('Authorized Signature', 10, sigY + 5);

  doc.line(100, sigY, 170, sigY);
  doc.text('Date', 100, sigY + 5);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text('Generated by Timor Payroll System', pageWidth / 2, 285, { align: 'center' });
  doc.text(`Generated on: ${format(new Date(), 'MMMM d, yyyy HH:mm')}`, pageWidth / 2, 290, { align: 'center' });

  // Save the PDF
  doc.save(`WIT-Return-${data.period.replace(' ', '-')}.pdf`);
}
